# Macrobond web API - Example for Oz Minerals

*Retrieving specific observations*

This notebook is designed to act as a template and guidline in which certain elements can be minipulated to get the desired outcome. Here we demonstrates how you can use the web API to pull out observations via a POST method, creating chunks to narrow down the universe and loop the requests to eventually fetch the data.

The POST FetchSeries endpoint also allows to fetch time series only when they have received updates compared to the last download.
For this workflow, we will use ifModifiedSince = LastModifiedTimeStamp.


*Full error handling is omitted for brevity*

***

## Importing packages

In [1]:
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session
import json
import pandas as pd
from pandas.io.json import json_normalize

***

## Authentication

If you have a Macrobond's web API account, enter your *client_id* and *client_secret* in a credentials.py file stored in the same location as this notebook.

In [2]:
# Please add your credentials to the file credentials.py included in the same directory as this notebook
import credentials
client_id = credentials.mbApiCredentials["clientId"]
client_secret = credentials.mbApiCredentials["secret"]

token_url="https://apiauth.macrobondfinancial.com/mbauth/connect/token"
client = client = BackendApplicationClient(client_id=client_id, scope="macrobond_web_api.read_mb macrobond_web_api.search_mb ")
mbapi = OAuth2Session(client=client)

***

## POST your universe

We are using FetchSeries below. We are creating three universes in total: Gold | Silver | Copper.
In this example, we will use the close price only but feel free to refer to the attached **Macrobond_Oz_Minerals_Universe.xlsx** file to user other items such as Open | High | Low | Volume | Open Interest.

In [3]:
def postAndDownloadMbApi(request, postDataDict):
  json_obj = json.dumps(postDataDict, ensure_ascii=True)
  url = "https://api.macrobondfinancial.com/v1/" + request
  # This is typically the first time when we do not yet have a token
  if not mbapi.authorized:
    mbapi.fetch_token(token_url=token_url, client_id=client_id, client_secret=client_secret)
  headers = {'Content-Type': 'application/json'}
  r = mbapi.post(url = url, headers = headers, data = json_obj)
  if r.status_code == 401:
    # If authorization failed, it is likely that the token has expired. Get a new one and try again.
    mbapi.fetch_token(token_url=token_url, client_id=client_id, client_secret=client_secret)
    r = mbapi.post(url = url, headers = headers, data = json_obj)
  r.raise_for_status()
  return r.content
  
gold = [
   {"name": "gc_c1_cl"},
   {"name": "gc_c2_cl"},
   {"name": "gc_c3_cl"},
   {"name": "gc_c4_cl"},
   {"name": "gc_c5_cl"},
   {"name": "gc_c6_cl"},
   {"name": "gc_c7_cl"},
   {"name": "gc_c8_cl"},
   {"name": "gc_c9_cl"},
   {"name": "gc_c10_cl"},
   {"name": "gc_c11_cl"},
   {"name": "gc_c12_cl"},
   {"name": "gc_c13_cl"},
   {"name": "gc_c14_cl"},
   {"name": "gc_c15_cl"},
   {"name": "gc_c16_cl"},
   {"name": "gc_c17_cl"},
   {"name": "gc_c18_cl"},
   {"name": "gc_c19_cl"},
   {"name": "gc_c20_cl"},
   {"name": "gc_c21_cl"},
   {"name": "gc_c22_cl"}
]

silver = [
   {"name": "si_c1_cl"},
   {"name": "si_c2_cl"},
   {"name": "si_c3_cl"},
   {"name": "si_c4_cl"},
   {"name": "si_c5_cl"},
   {"name": "si_c6_cl"},
   {"name": "si_c7_cl"},
   {"name": "si_c8_cl"},
   {"name": "si_c9_cl"},
   {"name": "si_c10_cl"},
   {"name": "si_c11_cl"},
   {"name": "si_c12_cl"},
   {"name": "si_c13_cl"},
   {"name": "si_c14_cl"},
   {"name": "si_c15_cl"},
   {"name": "si_c16_cl"},
   {"name": "si_c17_cl"},
   {"name": "si_c18_cl"},
   {"name": "si_c19_cl"},
   {"name": "si_c20_cl"}
]

copper = [
   {"name": "hg_c1_cl"},
   {"name": "hg_c2_cl"},
   {"name": "hg_c3_cl"},
   {"name": "hg_c4_cl"},
   {"name": "hg_c5_cl"},
   {"name": "hg_c6_cl"},
   {"name": "hg_c7_cl"},
   {"name": "hg_c8_cl"},
   {"name": "hg_c9_cl"},
   {"name": "hg_c10_cl"},
   {"name": "hg_c11_cl"},
   {"name": "hg_c12_cl"},
   {"name": "hg_c13_cl"},
   {"name": "hg_c14_cl"},
   {"name": "hg_c15_cl"},
   {"name": "hg_c16_cl"},
   {"name": "hg_c17_cl"},
   {"name": "hg_c18_cl"},
   {"name": "hg_c19_cl"},
   {"name": "hg_c20_cl"},
   {"name": "hg_c21_cl"},
   {"name": "hg_c22_cl"},
   {"name": "hg_c23_cl"},
   {"name": "hg_c24_cl"},
   {"name": "hg_c25_cl"},
   {"name": "hg_c26_cl"},
   {"name": "hg_c27_cl"},
   {"name": "hg_c28_cl"},
   {"name": "hg_c29_cl"},
   {"name": "hg_c30_cl"},
   {"name": "hg_c31_cl"},
   {"name": "hg_c32_cl"},
   {"name": "hg_c33_cl"},
   {"name": "hg_c34_cl"},
   {"name": "hg_c35_cl"},
   {"name": "hg_c36_cl"},
   {"name": "hg_c37_cl"},
   {"name": "hg_c38_cl"},
   {"name": "hg_c39_cl"},
   {"name": "hg_c40_cl"},
   {"name": "hg_c41_cl"}
]

In [8]:
d_gold = postAndDownloadMbApi("series/fetchseries", gold)
jdata_gold = json.loads(d_gold.decode('utf-8'))
df_gold = pd.json_normalize(jdata_gold)

d_silver = postAndDownloadMbApi("series/fetchseries", silver)
jdata_silver = json.loads(d_silver.decode('utf-8'))
df_silver = pd.json_normalize(jdata_silver)

d_copper = postAndDownloadMbApi("series/fetchseries", copper)
jdata_copper = json.loads(d_copper.decode('utf-8'))
df_copper = pd.json_normalize(jdata_copper)

In [9]:
df_gold_metadata = pd.DataFrame(df_gold,columns=['metadata.Name','metadata.LastModifiedTimeStamp','metadata.StartDate','metadata.EndDate','metadata.FullDescription'])
df_gold_metadata

,metadata.Name,metadata.LastModifiedTimeStamp,metadata.StartDate,metadata.EndDate,metadata.FullDescription
0,gc_c1_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 1st Position, Clos..."
1,gc_c2_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 2nd Position, Clos..."
2,gc_c3_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 3rd Position, Clos..."
3,gc_c4_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 4th Position, Clos..."
4,gc_c5_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 5th Position, Clos..."
5,gc_c6_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 6th Position, Clos..."
6,gc_c7_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 7th Position, Clos..."
7,gc_c8_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 8th Position, Clos..."
8,gc_c9_cl,2022-10-26T22:54:51+00:00,1974-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 9th Position, Clos..."
9,gc_c10_cl,2022-10-26T22:54:51+00:00,1975-01-03T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 10th Position, Clo..."
10,gc_c11_cl,2022-10-26T22:54:51+00:00,1977-04-28T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 11th Position, Clo..."
11,gc_c12_cl,2022-10-26T22:54:51+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 12th Position, Clo..."
12,gc_c13_cl,2022-10-26T22:54:51+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 13th Position, Clo..."
13,gc_c14_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 14th Position, Clo..."
14,gc_c15_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 15th Position, Clo..."
15,gc_c16_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 16th Position, Clo..."
16,gc_c17_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 17th Position, Clo..."
17,gc_c18_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 18th Position, Clo..."
18,gc_c19_cl,2022-10-26T22:54:51+00:00,1990-11-20T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 19th Position, Clo..."
19,gc_c20_cl,2022-10-26T22:54:51+00:00,1990-12-31T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 20th Position, Clo..."
20,gc_c21_cl,2022-10-26T22:54:51+00:00,1990-12-28T00:00:00,2022-10-26T00:00:00,"Gold, COMEX, Future, COMEX, 21st Position, Clo..."
21,gc_c22_cl,2022-07-27T22:40:10+00:00,1990-11-20T00:00:00,2022-07-27T00:00:00,"Gold, COMEX, Future, COMEX, 22nd Position, Clo..."

In [10]:
df_gold_data = pd.DataFrame(df_gold,columns=['metadata.Name','dates','values']).apply(pd.Series.explode).set_index(['metadata.Name'])
df_gold_data

                             dates  values
metadata.Name
gc_c1_cl       1974-12-31T00:00:00   182.5
gc_c1_cl       1975-01-01T00:00:00    None
gc_c1_cl       1975-01-02T00:00:00   173.5
gc_c1_cl       1975-01-03T00:00:00   173.5
gc_c1_cl       1975-01-06T00:00:00   173.4
...                            ...     ...
gc_c22_cl      2022-07-21T00:00:00  1956.5
gc_c22_cl      2022-07-22T00:00:00  1969.7
gc_c22_cl      2022-07-25T00:00:00  1961.6
gc_c22_cl      2022-07-26T00:00:00  1959.2
gc_c22_cl      2022-07-27T00:00:00  1960.8

[218738 rows x 2 columns]

In [11]:
df_silver_metadata = pd.DataFrame(df_silver,columns=['metadata.Name','metadata.LastModifiedTimeStamp','metadata.StartDate','metadata.EndDate','metadata.FullDescription'])
df_silver_metadata

,metadata.Name,metadata.LastModifiedTimeStamp,metadata.StartDate,metadata.EndDate,metadata.FullDescription
0,si_c1_cl,2022-10-26T22:55:31+00:00,1963-08-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 1st Position, Cl..."
1,si_c2_cl,2022-10-26T22:55:32+00:00,1963-11-29T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 2nd Position, Cl..."
2,si_c3_cl,2022-10-26T22:55:32+00:00,1963-06-13T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 3rd Position, Cl..."
3,si_c4_cl,2022-10-26T22:55:32+00:00,1963-06-13T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 4th Position, Cl..."
4,si_c5_cl,2022-10-26T22:55:32+00:00,1963-08-13T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 5th Position, Cl..."
5,si_c6_cl,2022-10-26T22:55:32+00:00,1963-10-01T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 6th Position, Cl..."
6,si_c7_cl,2022-10-26T22:55:31+00:00,1964-01-02T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 7th Position, Cl..."
7,si_c8_cl,2022-10-26T22:55:31+00:00,1964-03-31T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 8th Position, Cl..."
8,si_c9_cl,2022-10-26T22:55:32+00:00,1964-05-28T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 9th Position, Cl..."
9,si_c10_cl,2022-10-26T22:55:32+00:00,1964-07-31T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 10th Position, C..."
10,si_c11_cl,2022-10-26T22:55:32+00:00,1975-08-28T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 11th Position, C..."
11,si_c12_cl,2022-10-26T22:55:32+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 12th Position, C..."
12,si_c13_cl,2022-10-26T22:55:31+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 13th Position, C..."
13,si_c14_cl,2022-10-26T22:55:31+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 14th Position, C..."
14,si_c15_cl,2022-10-26T22:55:32+00:00,1992-10-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 15th Position, C..."
15,si_c16_cl,2022-10-26T22:55:32+00:00,1992-10-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 16th Position, C..."
16,si_c17_cl,2022-10-26T22:55:32+00:00,1992-10-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 17th Position, C..."
17,si_c18_cl,2022-10-26T22:55:32+00:00,1992-10-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 18th Position, C..."
18,si_c19_cl,2022-10-26T22:55:31+00:00,1992-10-30T00:00:00,2022-10-26T00:00:00,"Silver, NYMEX, Future, NYMEX, 19th Position, C..."
19,si_c20_cl,2022-09-28T22:42:47+00:00,1992-12-30T00:00:00,2022-09-28T00:00:00,"Silver, NYMEX, Future, NYMEX, 20th Position, C..."

In [12]:
df_silver_data = pd.DataFrame(df_silver,columns=['metadata.Name','dates','values']).apply(pd.Series.explode).set_index(['metadata.Name'])
df_silver_data

                             dates  values
metadata.Name
si_c1_cl       1963-08-30T00:00:00  1.2905
si_c1_cl       1963-09-03T00:00:00  1.2905
si_c1_cl       1963-09-04T00:00:00   1.292
si_c1_cl       1963-09-05T00:00:00   1.291
si_c1_cl       1963-09-06T00:00:00   1.293
...                            ...     ...
si_c20_cl      2022-09-22T00:00:00  22.231
si_c20_cl      2022-09-23T00:00:00  21.518
si_c20_cl      2022-09-26T00:00:00  21.082
si_c20_cl      2022-09-27T00:00:00  20.932
si_c20_cl      2022-09-28T00:00:00  21.471

[225104 rows x 2 columns]

In [13]:
df_copper_metadata = pd.DataFrame(df_copper,columns=['metadata.Name','metadata.LastModifiedTimeStamp','metadata.StartDate','metadata.EndDate','metadata.FullDescription'])
df_copper_metadata

,metadata.Name,metadata.LastModifiedTimeStamp,metadata.StartDate,metadata.EndDate,metadata.FullDescription
0,hg_c1_cl,2022-10-26T22:54:56+00:00,1959-07-02T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 1st Position, Cl..."
1,hg_c2_cl,2022-10-26T22:54:56+00:00,1959-07-02T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 2nd Position, Cl..."
2,hg_c3_cl,2022-10-26T22:54:56+00:00,1959-07-22T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 3rd Position, Cl..."
3,hg_c4_cl,2022-10-26T22:54:56+00:00,1959-10-06T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 4th Position, Cl..."
4,hg_c5_cl,2022-10-26T22:54:56+00:00,1959-11-11T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 5th Position, Cl..."
5,hg_c6_cl,2022-10-26T22:54:56+00:00,1963-01-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 6th Position, Cl..."
6,hg_c7_cl,2022-10-26T22:54:56+00:00,1971-10-28T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 7th Position, Cl..."
7,hg_c8_cl,2022-10-26T22:54:56+00:00,1971-11-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 8th Position, Cl..."
8,hg_c9_cl,2022-10-26T22:54:56+00:00,1972-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 9th Position, Cl..."
9,hg_c10_cl,2022-10-26T22:54:56+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 10th Position, C..."
10,hg_c11_cl,2022-10-26T22:54:56+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 11th Position, C..."
11,hg_c12_cl,2022-10-26T22:54:56+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 12th Position, C..."
12,hg_c13_cl,2022-10-26T22:54:56+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 13th Position, C..."
13,hg_c14_cl,2022-10-26T22:54:56+00:00,1977-08-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 14th Position, C..."
14,hg_c15_cl,2022-10-26T22:54:56+00:00,1985-09-03T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 15th Position, C..."
15,hg_c16_cl,2022-10-26T22:54:56+00:00,1989-06-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 16th Position, C..."
16,hg_c17_cl,2022-10-26T22:54:56+00:00,1989-06-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 17th Position, C..."
17,hg_c18_cl,2022-10-26T22:54:56+00:00,1989-06-30T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 18th Position, C..."
18,hg_c19_cl,2022-10-26T22:54:56+00:00,1994-04-28T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 19th Position, C..."
19,hg_c20_cl,2022-10-26T22:54:56+00:00,1995-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 20th Position, C..."
20,hg_c21_cl,2022-10-26T22:54:56+00:00,1995-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 21st Position, C..."
21,hg_c22_cl,2022-10-26T22:54:56+00:00,1995-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 22nd Position, C..."
22,hg_c23_cl,2022-10-26T22:54:56+00:00,1995-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 23rd Position, C..."
23,hg_c24_cl,2022-10-26T22:54:56+00:00,1995-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 24th Position, C..."
24,hg_c25_cl,2022-10-26T22:54:56+00:00,2005-08-31T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 25th Position, C..."
25,hg_c26_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 26th Position, C..."
26,hg_c27_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 27th Position, C..."
27,hg_c28_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 28th Position, C..."
28,hg_c29_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 29th Position, C..."
29,hg_c30_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 30th Position, C..."
30,hg_c31_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 31st Position, C..."
31,hg_c32_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 32nd Position, C..."
32,hg_c33_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 33rd Position, C..."
33,hg_c34_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 34th Position, C..."
34,hg_c35_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 35th Position, C..."
35,hg_c36_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 36th Position, C..."
36,hg_c37_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 37th Position, C..."
37,hg_c38_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 38th Position, C..."
38,hg_c39_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 39th Position, C..."
39,hg_c40_cl,2022-10-26T22:54:56+00:00,2010-09-17T00:00:00,2022-10-26T00:00:00,"Copper, COMEX, Future, COMEX, 40th Position, C..."
40,hg_c41_cl,2022-07-27T22:40:17+00:00,2021-02-25T00:00:00,2022-07-27T00:00:00,"Copper, COMEX, Future, COMEX, 41st Position, C..."

In [14]:
df_copper_data = pd.DataFrame(df_copper,columns=['metadata.Name','dates','values']).apply(pd.Series.explode).set_index(['metadata.Name'])
df_copper_data

                             dates  values
metadata.Name
hg_c1_cl       1959-07-02T00:00:00   0.293
hg_c1_cl       1959-07-06T00:00:00   0.291
hg_c1_cl       1959-07-07T00:00:00   0.282
hg_c1_cl       1959-07-08T00:00:00  0.2846
hg_c1_cl       1959-07-09T00:00:00   0.276
...                            ...     ...
hg_c41_cl      2022-07-21T00:00:00  3.5145
hg_c41_cl      2022-07-22T00:00:00   3.582
hg_c41_cl      2022-07-25T00:00:00   3.601
hg_c41_cl      2022-07-26T00:00:00   3.627
hg_c41_cl      2022-07-27T00:00:00   3.667

[305614 rows x 2 columns]

***

## Control for Updates

We now want to check whether our universe needs to be updated or not.
You can use the ifModifiedSince parameter within POST FetchSeries where it should correspond to the LastModifiedTimeStamp populated within the metadata of the initial load.

In this example, as we are using only two time series for the purpose of the example with a lower frequency than daily.
Feel free to create your universes with the names and LastModifiedTimeStamps of the time series in order to call them directly in the API call below.

The result will be in the same order as the request.

In [17]:
payload = [
   {"name": "usgdp", "ifModifiedSince": "2022-10-27T15:15:54.381Z"},
   {"name": "frcpi", "ifModifiedSince": "2022-10-27T15:15:54.381Z"},
]

d = postAndDownloadMbApi("series/fetchseries", payload)
jdata = json.loads(d.decode('utf-8'))
df = pd.json_normalize(jdata)
df

      errorText  errorCode
0  Not modified        304
1  Not modified        304

None of our time series have received any update. When there are updates, the time series will be downloaded by the request.